" Vundle
set rtp+=~/.vim/vundle.git/ 
call vundle#rc()

filetype plugin indent on

" Bundles
Bundle 'https://github.com/mileszs/ack.vim.git'
Bundle 'https://github.com/tpope/vim-endwise.git'
Bundle 'https://github.com/tpope/vim-rails.git'
Bundle 'https://github.com/tpope/vim-haml.git'
Bundle 'https://github.com/scrooloose/nerdtree.git'
Bundle 'https://github.com/tpope/vim-markdown.git'
Bundle 'https://github.com/msanders/snipmate.vim.git'
Bundle 'https://github.com/cakebaker/scss-syntax.vim.git'
Bundle 'https://github.com/davidoc/taskpaper.vim.git'
Bundle 'https://github.com/tpope/vim-surround.git'
Bundle 'https://github.com/tpope/vim-fugitive.git'
Bundle 'https://github.com/mattn/zencoding-vim.git'
Bundle 'https://github.com/duff/vim-scratch.git'
Bundle 'https://github.com/kogent/vim-peepopen.git'
Bundle 'https://github.com/godlygeek/tabular.git'
Bundle 'https://github.com/ddollar/nerdcommenter.git'
Bundle 'https://github.com/robgleeson/vim-markdown-preview.git'
Bundle 'https://github.com/altercation/vim-colors-solarized.git'
Bundle 'https://github.com/mr-szymanski/prefixr.git'
Bundle 'https://github.com/kchmck/vim-coffee-script.git'
"Bundle 'https://github.com/immerzeel/vim-remember-the-milk.git'

" Syntax & colors
syntax on
colors solarized

" Tabs
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab

" Ack
set grepprg=rak

" Encoding
set encoding=utf-8

" Searching
set ignorecase
set smartcase
set gdefault
set incsearch
set showmatch
set hlsearch

" Handle long lines
set wrap
set textwidth=79
set formatoptions=qrn1
set colorcolumn=81

" Moving around
nmap j gj
nmap k gk

" F1 annoyance
inoremap <F1> <ESC>
nnoremap <F1> <ESC>
vnoremap <F1> <ESC>

" jj
imap jj <Esc>

" ; == :
nnoremap ; :

" Save on tab-out
au FocusLost * :wa

" Split windows
nmap <leader>w <C-w>v<C-w>1
nmap <D-w> <C-w>v<C-w>1<CR>
nmap <C-h> <C-w>h
nmap <C-j> <C-w>j
nmap <C-k> <C-w>k
nmap <C-l> <C-w>l

" Folding settings
set foldmethod=indent   "indent based on syntax
set foldnestmax=3       "deepest fold is 3 levels
set foldlevel=3
set nofoldenable        "dont fold by default

" Show line numbering and current line
set number
set numberwidth=4
set cursorline

set lazyredraw " no redraw when running macros

" Status line
set statusline=%f "tail of the filename
set statusline+=\ 
"set statusline+=%h      "help file flag
set statusline+=%y      "filetype
set statusline+=%r      "read only flag
set statusline+=%1*%m%*      "modified flag
set statusline+=%=      "left/right aligned items separated
set statusline+=%#warningmsg#
set statusline+=%*\ 
set statusline+=%-10.(%l,%c%V%)\ %P "ruler

" Sane backspace behaviour
set backspace=indent,eol,start

" These file are ruby!
au BufRead,BufNewFile {Gemfile,Rakefile,Thorfile,config.ru,Rules} set ft=ruby

" ...and these are CoffeeScript!
au BufNewFile,BufReadPost *.coffee setl foldmethod=indent nofoldenable
au BufNewFile,BufReadPost *.coffee setl shiftwidth=2 expandtab

" Leader key
let mapleader=","

" Backup & swaps
set backup
set backupdir=~/.vim/backup
set directory=~/.vim/tmp

" NERD tree
map <silent> <F2> <ESC>:NERDTreeToggle<CR>
nmap <silent> <leader>ft :NERDTreeFind<CR>

" Command-T
map <silent> <D-t> <leader>p

" Move line(s) of text using Alt+j/k
nmap <silent> <A-j> :m+<CR>==
nmap <silent> <A-k> :m-2<CR>==
imap <silent> <A-j> <Esc>:m+<CR>==gi
imap <silent> <A-k> <Esc>:m-2<CR>==gi
vmap <silent> <A-j> :m'>+<CR>gv=gv
vmap <silent> <A-k> :m-2<CR>gv=gv

" Preserve selection when indenting
vmap > >gv
vmap < <gv

" Indenting with Cmd + [ and ]
nmap <D-[> <<
nmap <D-]> >>
nmap <D-h> <<
nmap <D-l> >>
vmap <D-[> <gv
vmap <D-]> >gv
imap <D-[> <ESC><<gi
imap <D-]> <ESC>>>gi


" Remove the annoying icons - we should use keyboard anyway!
if has("gui_running")
    set guioptions=egmrt
endif

" Less CSS is awesome.
au BufNewFile,BufRead *.less set filetype=less

if has("gui_running") && system('ps xw | grep "Vim -psn" | grep -vc grep') > 0
  " Get the value of $PATH from a login shell.
  " If your shell is not on this list, it may be just because we have not
  " tested it.  Try adding it to the list and see if it works.  If so,
  " please post a note to the vim-mac list!
  if $SHELL =~ '/\(sh\|csh\|bash\|tcsh\|zsh\)$'
    let s:path = system("echo echo VIMPATH'${PATH}' | $SHELL -l")
    let $PATH = matchstr(s:path, 'VIMPATH\zs.\{-}\ze\n')
  endif
endif

" Tabular
nmap <Leader>a= :Tabularize /=<CR>
vmap <Leader>a= :Tabularize /=<CR>
nmap <Leader>a: :Tabularize /:\zs<CR>
vmap <Leader>a: :Tabularize /:\zs<CR>

" Capitalize
if (&tildeop)
  nmap gcw guw~l
  nmap gcW guW~l
  nmap gciw guiw~l
  nmap gciW guiW~l
  nmap gcis guis~l
  nmap gc$ gu$~l
  nmap gcgc guu~l
  nmap gcc guu~l
  vmap gc gu~l
else
  nmap gcw guw~h
  nmap gcW guW~h
  nmap gciw guiw~h
  nmap gciW guiW~h
  nmap gcis guis~h
  nmap gc$ gu$~h
  nmap gcgc guu~h
  nmap gcc guu~h
  vmap gc gu~h
endif

vmap <Leader>w :Prefixr<CR>

" ZenCoding
let g:user_zen_settings = {
\  'indentation' : '  ',
\  'php' : {
\    'extends' : 'html',
\    'filters' : 'c',
\  },
\  'xml' : {
\    'extends' : 'html',
\  },
\  'haml' : {
\    'extends' : 'html',
\  },
\  'less' : {
\    'extends' : 'css',
\  },
\  'sass' : {
\    'extends' : 'css',
\  },
\}

let g:user_zen_leader_key = '<D-e>'

let g:use_zen_complete_tag = 1

" Scratch.vim
function! ToggleScratch()
  if expand('%') == g:ScratchBufferName
    quit
  else
    Sscratch
  endif
endfunction

map <leader>s :call ToggleScratch()<CR>

if has("gui_macvim")
  let macvim_hig_shift_movement = 1
endif

