" Pathogen
filetype off
call pathogen#runtime_append_all_bundles()
call pathogen#helptags()
filetype indent on

" Syntax & colors
syntax on
colors mustang

" Tabs
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab

" Ack
set grepprg=ack
set grepformat=%f:%l:%m

" Encoding
set encoding=utf-8

" Searching
set ignorecase
set smartcase
set gdefault
set incsearch
set showmatch
set hlsearch

" Handle long lines
set wrap
set textwidth=79
set formatoptions=qrn1
set colorcolumn=81

" Moving around
nnoremap j gj
nnoremap k gk

" F1 annoyance
inoremap <F1> <ESC>
nnoremap <F1> <ESC>
vnoremap <F1> <ESC>

" ; == :
nnoremap ; :

" Save on tab-out
au FocusLost * :wa

" Split windows
nnoremap <leader>w <C-w>v<C-w>1
nnoremap <D-w> <C-w>v<C-w>1<CR>
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Folding settings
set foldmethod=indent   "indent based on syntax
set foldnestmax=3       "deepest fold is 3 levels
set foldlevel=3
set nofoldenable        "dont fold by default

" Show line numbering and current line
set number
set numberwidth=4
set cursorline

set lazyredraw " no redraw when running macros

" Status line
set statusline=%f "tail of the filename
set statusline+=\ 
"set statusline+=%h      "help file flag
set statusline+=%y      "filetype
set statusline+=%r      "read only flag
set statusline+=%1*%m%*      "modified flag
set statusline+=%=      "left/right aligned items separated
set statusline+=%#warningmsg#
set statusline+=%*\ 
set statusline+=%-10.(%l,%c%V%)\ %P "ruler

" Sane backspace behaviour
set backspace=indent,eol,start

" These file are ruby!
au BufRead,BufNewFile {Gemfile,Rakefile,Thorfile,config.ru,Rules} set ft=ruby

" Leader key
let mapleader=","

" NERD tree
map <silent> <F2> <ESC>:NERDTreeToggle<CR>
nmap <silent> <leader>ft :NERDTreeFind<CR>

" Command-T
map <silent> <D-t> <leader>p

" Move line(s) of text using Alt+j/k
nnoremap <silent> <A-j> :m+<CR>==
nnoremap <silent> <A-k> :m-2<CR>==
inoremap <silent> <A-j> <Esc>:m+<CR>==gi
inoremap <silent> <A-k> <Esc>:m-2<CR>==gi
vnoremap <silent> <A-j> :m'>+<CR>gv=gv
vnoremap <silent> <A-k> :m-2<CR>gv=gv

" Preserve selection when indenting
vmap > >gv
vmap < <gv

" Indenting with Cmd + [ and ]
nmap <D-[> <<
nmap <D-]> >>
nmap <D-h> <<
nmap <D-l> >>
vmap <D-[> <gv
vmap <D-]> >gv
imap <D-[> <ESC><<gi
imap <D-]> <ESC>>>gi


" Remove the annoying icons - we should use keyboard anyway!
if has("gui_running")
    set guioptions=egmrt
endif

" Less CSS is awesome.
au BufNewFile,BufRead *.less set filetype=less

if has("gui_running") && system('ps xw | grep "Vim -psn" | grep -vc grep') > 0
  " Get the value of $PATH from a login shell.
  " If your shell is not on this list, it may be just because we have not
  " tested it.  Try adding it to the list and see if it works.  If so,
  " please post a note to the vim-mac list!
  if $SHELL =~ '/\(sh\|csh\|bash\|tcsh\|zsh\)$'
    let s:path = system("echo echo VIMPATH'${PATH}' | $SHELL -l")
    let $PATH = matchstr(s:path, 'VIMPATH\zs.\{-}\ze\n')
  endif
endif

" Tabular
if exists(":Tabularize")
  nmap <Leader>a= :Tabularize /=<CR>
  vmap <Leader>a= :Tabularize /=<CR>
  nmap <Leader>a: :Tabularize /:\zs<CR>
  vmap <Leader>a: :Tabularize /:\zs<CR>
endif

" Capitalize
if (&tildeop)
  nmap gcw guw~l
  nmap gcW guW~l
  nmap gciw guiw~l
  nmap gciW guiW~l
  nmap gcis guis~l
  nmap gc$ gu$~l
  nmap gcgc guu~l
  nmap gcc guu~l
  vmap gc gu~l
else
  nmap gcw guw~h
  nmap gcW guW~h
  nmap gciw guiw~h
  nmap gciW guiW~h
  nmap gcis guis~h
  nmap gc$ gu$~h
  nmap gcgc guu~h
  nmap gcc guu~h
  vmap gc gu~h
endif

" ZenCoding
let g:user_zen_settings = {
\  'indentation' : '  ',
\  'php' : {
\    'extends' : 'html',
\    'filters' : 'c',
\  },
\  'xml' : {
\    'extends' : 'html',
\  },
\  'haml' : {
\    'extends' : 'html',
\  },
\  'less' : {
\    'extends' : 'css',
\  },
\  'sass' : {
\    'extends' : 'css',
\  },
\}

let g:user_zen_leader_key = '<D-e>'

let g:use_zen_complete_tag = 1

" Scratch.vim
function! ToggleScratch()
  if expand('%') == g:ScratchBufferName
    quit
  else
    Sscratch
  endif
endfunction

map <leader>s :call ToggleScratch()<CR>

